version: '3'
services:
 mongodb:
  image: mongo:latest
#   env_file:
   # .env
  ports:
   - 27017:27017
  container_name: mongoLog
  restart: unless-stopped
  volumes:
   - db-data:/data/db
   - mongo-config:/data/configdb
volumes:
 db-data:
 mongo-config: